version: '3'

services:
  puppet:
    container_name: puppet
    hostname: ${PUPPETSERVER_HOSTNAME}
    restart: unless-stopped
    build: docker/puppetserver
    ports:
      - "8140:8140"
    volumes:
      - ./code:/etc/puppetlabs/code/
      - ./puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ./puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/
    # In some cases unqualified hostnames can have the .local suffix
    # added, I've seen this under Docker of Mac Beta for instance.
    # Due to needing to access PuppetDB on same hostame as signed in the
    # certificate you may need to uncommant the following lines
    environment:
      - "container=docker"
      - "FACTER_role=puppet"
      - "FACTER_cluster=puppet"
      - "PUPPETDB_SERVER_URLS=${PUPPETDB_SERVER_URLS}"
      - "PUPPETSERVER_JAVA_ARGS=${PUPPETSERVER_JAVA_ARGS}"
    networks:
      - puppet

  puppetdbpostgres:
    container_name: postgres
    hostname: postgres
    image: puppet/puppetdb-postgres:9.6.3
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - "container=docker"
    expose:
      - "5432"
    volumes:
      - ./puppetdb-postgres/data:/var/lib/postgresql/data/
    networks:
      - puppet

  puppetdb:
    container_name: puppetdb
    hostname: puppetdb
    restart: unless-stopped
    build: docker/puppetdb
    ports:
      - "8081:8081"
    volumes:
      - ./puppetdb/ssl:/etc/puppetlabs/puppet/ssl/
    environment:
      - "container=docker"
      - "FACTER_role=puppetdb"
      - "FACTER_cluster=puppet"
      - "PUPPETDB_JAVA_ARGS=${PUPPETDB_JAVA_ARGS}"
      - "VIRTUAL_HOST=puppetb.${DNSDOMAIN}"
      - "VIRTUAL_PORT=8080"
    networks:
      - puppet

  puppetboard:
    image: ambakshi/puppetboard:0.2.2
    restart: unless-stopped
    environment:
      - "VIRTUAL_HOST=puppetboard.${DNSDOMAIN}"
      - "LETSENCRYPT_HOST=puppetboard.${DNSDOMAIN}"
      - "container=docker"
      - "LETSENCRYPT_EMAIL=${EMAIL}"
    networks:
      - puppet

  puppetexplorer:
    image: puppet/puppetexplorer
    restart: unless-stopped
    read_only: true
    environment:
      - "VIRTUAL_HOST=puppetexplorer.${DNSDOMAIN}"
      - "LETSENCRYPT_HOST=puppetexplorer.${DNSDOMAIN}"
      - "LETSENCRYPT_EMAIL=${EMAIL}"
    networks:
      - puppet
    environment:
      - "container=docker"

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - puppet
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

networks:
  puppet:
    driver: bridge

#   nginx-letsencrypt-proxy:
#     image: jrcs/letsencrypt-nginx-proxy-companion
#     restart: unless-stopped
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - /etc/nginx/certs:/etc/nginx/certs:rw
#     volumes_from:
#       - nginx-proxy
